### ISSUE TITLE
Honor cairo-lint config from Scarb.toml in LS' linter plugin

### ISSUE THREAD

**Issue by mkaput** [software-mansion/cairols#483]
### Problem

CairoLS does not read `[too.cairo-lint]` section from Scarb.toml, thus it does not handle `nopanic`.

### Steps

Put the following in Scarb.toml:

```toml
[tool.cairo-lint]
nopanic = true
```

The panic lint should disappear in the Problems panel.

### Scarb Version

```text

```
